package com.example.myapplication.models;

import java.util.HashMap;
import java.util.Map;

public class Rates {
    private float AED;
    private float AFN;
    private float ALL;
    private float AMD;
    private float ANG;
    private float AOA;
    private float ARS;
    private float AUD;
    private float AWG;
    private float AZN;
    private float BAM;
    private float BBD;
    private float BDT;
    private float BGN;
    private float BHD;
    private float BIF;
    private float BMD;
    private float BND;
    private float BOB;
    private float BRL;
    private float BSD;
    private float BTC;
    private float BTN;
    private float BWP;
    private float BYN;
    private float BZD;
    private float CAD;
    private float CDF;
    private float CHF;
    private float CLF;
    private float CLP;
    private float CNH;
    private float CNY;
    private float COP;
    private float CRC;
    private float CUC;
    private float CUP;
    private float CVE;
    private float CZK;
    private float DJF;
    private float DKK;
    private float DOP;
    private float DZD;
    private float EGP;
    private float ERN;
    private float ETB;
    private float EUR;
    private float FJD;
    private float FKP;
    private float GBP;
    private float GEL;
    private float GGP;
    private float GHS;
    private float GIP;
    private float GMD;
    private float GNF;
    private float GTQ;
    private float GYD;
    private float HKD;
    private float HNL;
    private float HRK;
    private float HTG;
    private float HUF;
    private float IDR;
    private float ILS;
    private float IMP;
    private float INR;
    private float IQD;
    private float IRR;
    private float ISK;
    private float JEP;
    private float JMD;
    private float JOD;
    private float JPY;
    private float KES;
    private float KGS;
    private float KHR;
    private float KMF;
    private float KPW;
    private float KRW;
    private float KWD;
    private float KYD;
    private float KZT;
    private float LAK;
    private float LBP;
    private float LKR;
    private float LRD;
    private float LSL;
    private float LYD;
    private float MAD;
    private float MDL;
    private float MGA;
    private float MKD;
    private float MMK;
    private float MNT;
    private float MOP;
    private float MRU;
    private float MUR;
    private float MVR;
    private float MWK;
    private float MXN;
    private float MYR;
    private float MZN;
    private float NAD;
    private float NGN;
    private float NIO;
    private float NOK;
    private float NPR;
    private float NZD;
    private float OMR;
    private float PAB;
    private float PEN;
    private float PGK;
    private float PHP;
    private float PKR;
    private float PLN;
    private float PYG;
    private float QAR;
    private float RON;
    private float RSD;
    private float RUB;
    private float RWF;
    private float SAR;
    private float SBD;
    private float SCR;
    private float SDG;
    private float SEK;
    private float SGD;
    private float SHP;
    private float SLL;
    private float SOS;
    private float SRD;
    private float SSP;
    private float STD;
    private float STN;
    private float SVC;
    private float SYP;
    private float SZL;
    private float THB;
    private float TJS;
    private float TMT;
    private float TND;
    private float TOP;
    private float TRY;
    private float TTD;
    private float TWD;
    private float TZS;
    private float UAH;
    private float UGX;
    private float USD;
    private float UYU;
    private float UZS;
    private float VES;
    private float VND;
    private float VUV;
    private float WST;
    private float XAF;
    private float XAG;
    private float XAU;
    private float XCD;
    private float XDR;
    private float XOF;
    private float XPD;
    private float XPF;
    private float XPT;
    private float YER;
    private float ZAR;
    private float ZMW;
    private float ZWL;

    // Getters and setters for each currency omitted for brevity

    public Map<String, Float> toMap() {
        Map<String, Float> ratesMap = new HashMap<>();
        ratesMap.put("AED", AED);
        ratesMap.put("AFN", AFN);
        ratesMap.put("ALL", ALL);
        ratesMap.put("AMD", AMD);
        ratesMap.put("ANG", ANG);
        ratesMap.put("AOA", AOA);
        ratesMap.put("ARS", ARS);
        ratesMap.put("AUD", AUD);
        ratesMap.put("AWG", AWG);
        ratesMap.put("AZN", AZN);
        ratesMap.put("BAM", BAM);
        ratesMap.put("BBD", BBD);
        ratesMap.put("BDT", BDT);
        ratesMap.put("BGN", BGN);
        ratesMap.put("BHD", BHD);
        ratesMap.put("BIF", BIF);
        ratesMap.put("BMD", BMD);
        ratesMap.put("BND", BND);
        ratesMap.put("BOB", BOB);
        ratesMap.put("BRL", BRL);
        ratesMap.put("BSD", BSD);
        ratesMap.put("BTC", BTC);
        ratesMap.put("BTN", BTN);
        ratesMap.put("BWP", BWP);
        ratesMap.put("BYN", BYN);
        ratesMap.put("BZD", BZD);
        ratesMap.put("CAD", CAD);
        ratesMap.put("CDF", CDF);
        ratesMap.put("CHF", CHF);
        ratesMap.put("CLF", CLF);
        ratesMap.put("CLP", CLP);
        ratesMap.put("CNH", CNH);
        ratesMap.put("CNY", CNY);
        ratesMap.put("COP", COP);
        ratesMap.put("CRC", CRC);
        ratesMap.put("CUC", CUC);
        ratesMap.put("CUP", CUP);
        ratesMap.put("CVE", CVE);
        ratesMap.put("CZK", CZK);
        ratesMap.put("DJF", DJF);
        ratesMap.put("DKK", DKK);
        ratesMap.put("DOP", DOP);
        ratesMap.put("DZD", DZD);
        ratesMap.put("EGP", EGP);
        ratesMap.put("ERN", ERN);
        ratesMap.put("ETB", ETB);
        ratesMap.put("EUR", EUR);
        ratesMap.put("FJD", FJD);
        ratesMap.put("FKP", FKP);
        ratesMap.put("GBP", GBP);
        ratesMap.put("GEL", GEL);
        ratesMap.put("GGP", GGP);
        ratesMap.put("GHS", GHS);
        ratesMap.put("GIP", GIP);
        ratesMap.put("GMD", GMD);
        ratesMap.put("GNF", GNF);
        ratesMap.put("GTQ", GTQ);
        ratesMap.put("GYD", GYD);
        ratesMap.put("HKD", HKD);
        ratesMap.put("HNL", HNL);
        ratesMap.put("HRK", HRK);
        ratesMap.put("HTG", HTG);
        ratesMap.put("HUF", HUF);
        ratesMap.put("IDR", IDR);
        ratesMap.put("ILS", ILS);
        ratesMap.put("IMP", IMP);
        ratesMap.put("INR", INR);
        ratesMap.put("IQD", IQD);
        ratesMap.put("IRR", IRR);
        ratesMap.put("ISK", ISK);
        ratesMap.put("JEP", JEP);
        ratesMap.put("JMD", JMD);
        ratesMap.put("JOD", JOD);
        ratesMap.put("JPY", JPY);
        ratesMap.put("KES", KES);
        ratesMap.put("KGS", KGS);
        ratesMap.put("KHR", KHR);
        ratesMap.put("KMF", KMF);
        ratesMap.put("KPW", KPW);
        ratesMap.put("KRW", KRW);
        ratesMap.put("KWD", KWD);
        ratesMap.put("KYD", KYD);
        ratesMap.put("KZT", KZT);
        ratesMap.put("LAK", LAK);
        ratesMap.put("LBP", LBP);
        ratesMap.put("LKR", LKR);
        ratesMap.put("LRD", LRD);
        ratesMap.put("LSL", LSL);
        ratesMap.put("LYD", LYD);
        ratesMap.put("MAD", MAD);
        ratesMap.put("MDL", MDL);
        ratesMap.put("MGA", MGA);
        ratesMap.put("MKD", MKD);
        ratesMap.put("MMK", MMK);
        ratesMap.put("MNT", MNT);
        ratesMap.put("MOP", MOP);
        ratesMap.put("MRU", MRU);
        ratesMap.put("MUR", MUR);
        ratesMap.put("MVR", MVR);
        ratesMap.put("MWK", MWK);
        ratesMap.put("MXN", MXN);
        ratesMap.put("MYR", MYR);
        ratesMap.put("MZN", MZN);
        ratesMap.put("NAD", NAD);
        ratesMap.put("NGN", NGN);
        ratesMap.put("NIO", NIO);
        ratesMap.put("NOK", NOK);
        ratesMap.put("NPR", NPR);
        ratesMap.put("NZD", NZD);
        ratesMap.put("OMR", OMR);
        ratesMap.put("PAB", PAB);
        ratesMap.put("PEN", PEN);
        ratesMap.put("PGK", PGK);
        ratesMap.put("PHP", PHP);
        ratesMap.put("PKR", PKR);
        ratesMap.put("PLN", PLN);
        ratesMap.put("PYG", PYG);
        ratesMap.put("QAR", QAR);
        ratesMap.put("RON", RON);
        ratesMap.put("RSD", RSD);
        ratesMap.put("RUB", RUB);
        ratesMap.put("RWF", RWF);
        ratesMap.put("SAR", SAR);
        ratesMap.put("SBD", SBD);
        ratesMap.put("SCR", SCR);
        ratesMap.put("SDG", SDG);
        ratesMap.put("SEK", SEK);
        ratesMap.put("SGD", SGD);
        ratesMap.put("SHP", SHP);
        ratesMap.put("SLL", SLL);
        ratesMap.put("SOS", SOS);
        ratesMap.put("SRD", SRD);
        ratesMap.put("SSP", SSP);
        ratesMap.put("STD", STD);
        ratesMap.put("STN", STN);
        ratesMap.put("SVC", SVC);
        ratesMap.put("SYP", SYP);
        ratesMap.put("SZL", SZL);
        ratesMap.put("THB", THB);
        ratesMap.put("TJS", TJS);
        ratesMap.put("TMT", TMT);
        ratesMap.put("TND", TND);
        ratesMap.put("TOP", TOP);
        ratesMap.put("TRY", TRY);
        ratesMap.put("TTD", TTD);
        ratesMap.put("TWD", TWD);
        ratesMap.put("TZS", TZS);
        ratesMap.put("UAH", UAH);
        ratesMap.put("UGX", UGX);
        ratesMap.put("USD", USD);
        ratesMap.put("UYU", UYU);
        ratesMap.put("UZS", UZS);
        ratesMap.put("VES", VES);
        ratesMap.put("VND", VND);
        ratesMap.put("VUV", VUV);
        ratesMap.put("WST", WST);
        ratesMap.put("XAF", XAF);
        ratesMap.put("XAG", XAG);
        ratesMap.put("XAU", XAU);
        ratesMap.put("XCD", XCD);
        ratesMap.put("XDR", XDR);
        ratesMap.put("XOF", XOF);
        ratesMap.put("XPD", XPD);
        ratesMap.put("XPF", XPF);
        ratesMap.put("XPT", XPT);
        ratesMap.put("YER", YER);
        ratesMap.put("ZAR", ZAR);
        ratesMap.put("ZMW", ZMW);
        ratesMap.put("ZWL", ZWL);
        return ratesMap;
    }
}
